"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

a=6#hexagonal 2. basamak
b=5#pentagonal 2. basamak
c=3#triangle 2. basamak

i=7 #pentagonal 3. fark
j=9 #hexagonal 3. fark
k=3 #triangular 3. fark
while True:
    if a>40755 and a==b==c:
        break
    a += j
    j+=4
    while b < a:
        b += i
        i += 3
        while c<b:
            c+=k
            k+=1
print(a)
